trigger:
- submit

stages:
- stage: Test
  jobs:
  - job: "linux"
    pool:
      vmImage: "ubuntu-16.04"
    steps:
    - script: sudo apt update && sudo apt install openjdk-8-jdk && sudo apt install ant
      displayName: Install dependency
    - script: export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8 && cd acmdb-lab1 && ant clean && ant test && ant systemtest
      displayName: Run test and system test of lab1
    - script: export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8 && cd acmdb-lab2 && ant clean && ant test && ant systemtest
      displayName: Run test and system test of lab2
    - script: export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8 && cd acmdb-lab3 && ant clean && ant test && ant systemtest
      displayName: Run test and system test of lab3